version: '3.6'

services:
  mongo:
    container_name: mongo
    image: mongo:4.2.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./database/mongo:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo